# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
